// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_eOCTq_8qMvt2kCeyZgsqJGKdZ43FxOE',
    appId: '1:487102250981:web:f0b0d4baa8b6d88de5390c',
    messagingSenderId: '487102250981',
    projectId: 'employer-employee-app',
    authDomain: 'employer-employee-app.firebaseapp.com',
    storageBucket: 'employer-employee-app.appspot.com',
    measurementId: 'G-J6WM1GYLM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3e_nbRryLFBTZxBi_blOfxHIzdXBXp8',
    appId: '1:487102250981:android:f9c61746fb10daf9e5390c',
    messagingSenderId: '487102250981',
    projectId: 'employer-employee-app',
    storageBucket: 'employer-employee-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgKS4SOsnLPkdOYifSHm0KA2cL2HwORR4',
    appId: '1:487102250981:ios:f0741c13d26ba01ae5390c',
    messagingSenderId: '487102250981',
    projectId: 'employer-employee-app',
    storageBucket: 'employer-employee-app.appspot.com',
    iosBundleId: 'com.example.employerV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgKS4SOsnLPkdOYifSHm0KA2cL2HwORR4',
    appId: '1:487102250981:ios:069d865413317a54e5390c',
    messagingSenderId: '487102250981',
    projectId: 'employer-employee-app',
    storageBucket: 'employer-employee-app.appspot.com',
    iosBundleId: 'com.example.employerV1.RunnerTests',
  );
}
